capture: Remove loading wait
YaLTeR/bxt-rs pull request #55
Opened 2022-11-20 02:06 UTC by khanghugo

Recording normally would have loading. Here is a recording with lots of segments.

https://user-images.githubusercontent.com/29143195/202879114-02ab1feb-d821-4f17-b2c9-b077560f6acc.mp4

Here is one without loading. 

https://user-images.githubusercontent.com/29143195/202879124-a0059725-377b-4829-bdb7-0496491e3741.mp4

The `frame_count` could be changed around to omit early frames entirely. Though it might come at a cost of recording become janky. Some frames are broken as #2 mentions. That would need something else.

2022-11-20 02:45 UTC, khanghugo commented
Just realize I need to put a check whether it is demo is playing....

2022-11-20 03:11 UTC, khanghugo commented
Hmmm, it is still not quite working right.

2022-11-20 03:45 UTC, khanghugo commented
That one works but the last demo won't skip the loading because right now I have no idea how to check whether a demo is going to be played. Trying to approach the other way that the game is being played but not the demo but it seems bit complicated now.

2022-11-20 08:31 UTC, khanghugo commented
This should be better. It will start recording as soon as the game is done loading in general, not just limited to demo anymore. However, the fact that it will record when the game is loaded means recording the game when a map is not running will not record anything. But if prompted to a map, it will record right away. Maybe if that is needed then that could be the default behavior and extra cvar or this could be instead and there is another cvar (like `_bxt_cap_all_states`).

2022-11-22 00:25 UTC, YaLTeR commented
So, some thoughts on this:
1. How useful is *imperfect* removing loads? Like, if you're editing a segmented run, then with *imperfect* load removal you will still need to make the same number of cuts, but now they are smaller and harder to notice, making it more difficult rather than easier, right? Are there any other use-cases where this helps?
2. Does this implementation not break audio sync? I.e. what happens to the audio for the skipped frames.
3. > recording the game when a map is not running will not record anything

    Yeah, it's confusing if the default bxt_cap_start will just randomly not record something. Maybe there should be a separate command for starting a segmented run recording that will make it obvious that it only records demos and skips the loading parts. Although, we should also consider the case of live-recording TASes without loading frames -- how much sense that makes (i.e. does cutting out loads always produce nice footage, does it preserve audio sync).

2022-11-22 04:54 UTC, khanghugo commented
1. I think I choose my words poorly. This pretty much eliminates all of the game loading frames, which happens on the last frame of the last demo that has the next demo (or the first demo that needs some game loading, or just not being in the game in general). The broken thing I want to say is the broken early frames, which is not omitted right now because they are not part of the loading thing. That would be for issue #24. I just hope that this would help with putting the videos together easier. There is this `frame_count` I add that can help with aggressively cutting broken/unneeded frames that are not part of the loading. It is there. I think it is just me that wanting to record and be done without any much post-edit such as pointing out certain frames to cut. Overall, I think this would help with a portion of that goal where we can record and be done. It now just needs some fixes for aforementioned issue and it is all good.
2. I can make some tests with sound and see. But I don't think it would desync since this just squashes all the events happening during the load time to one single "time_passed". I can get some tests done and show more. Here is again a video and the sound comes out good. Could be 1 frame off, I don't know but there are 32 segments in this.

https://user-images.githubusercontent.com/29143195/203222182-e43f64b5-956a-4e98-afa9-103208b46046.mp4

3. I guess this will stay put here until #53 is properly done then? Also another fix for the mentioned issue is out.

2022-11-22 04:56 UTC, YaLTeR commented
@SmileyAG what do you think from segmented run rendering perspective?

2022-11-26 20:46 UTC, SmileyAG commented
> 



> @SmileyAG what do you think from segmented run rendering perspective?

I think it's ok to remove wait gaps since for rendering I'm always memorise at my head all transitions per the next demos after a multiple times of playback, and cuz anyway later I had to re-record audiotrack of some demo or with enabled cmd like `bxt_fade_remove 1`, so that ain't make for me a issue.

2022-11-27 05:46 UTC, khanghugo commented
:+1:

I am still wondering how this would get implemented. Yalter does mention there could be some intentions of just recording to see things. If we were to have a command to record for segmented run then we might have another `bxt_cap_start`. I also think of another use case for recording mentioned in #56; so we might have one more extra `bxt_cap_start` if that were to follow. I think the simplest thing would just having a cvar to explicitly enable these things. Something like `bxt_cap_remove_loading` suits this.

2022-11-29 06:08 UTC, khanghugo commented
Here are some testings. 


This video is the normal and this commit with audio on top of another. Not sure how helpful it is. 
https://user-images.githubusercontent.com/29143195/204451835-1ea3415a-d8cc-464b-8485-f1333f529543.mp4

Here is some waveform with video toggled off and on occasionally to see that videos are matched.
[Screencast from 2022-11-29 01-01-22.webm](https://user-images.githubusercontent.com/29143195/204451953-233c4488-781b-4643-8fb9-86f885d6cafa.webm)

2022-11-29 07:19 UTC, khanghugo commented
Here is how it does with live TAS recording.
Without cut:

https://user-images.githubusercontent.com/29143195/204463817-e8a226b3-76af-4897-8aee-0b1f910363ed.mp4

With cut:

https://user-images.githubusercontent.com/29143195/204463885-3e48e9f5-ea87-43b3-8b2a-96e0f244fb4d.mp4

A selected portion from no cut that I edit myself to see how it compares with this:

https://user-images.githubusercontent.com/29143195/204464042-87acc389-9d93-4ace-9acf-2e39cc98000f.mp4

2022-12-04 22:47 UTC, khanghugo commented
Hmmm, I thought I sync the change so your forced changes will get here also.... Welp, feel free to force push that.
This one will have the `bxt_cap_seemless` cvar that is `1` by default to skip the broken frames. Values greater than 1 can skip extra frames at the beginning, at least for now until there is a fix for the viewmodel frame thing (still, some frames before that viewmodel frames are broken and can be skipped).

I think it should be on by default because I think when people want to record, they wouldn't want to record the main menu as soon as they start the client.

2022-12-05 22:03 UTC, khanghugo commented on src/modules/capture/mod.rs
> +            if cls_demos.demoplayback == 1 && frame_count < BXT_CAP_SEEMLESS.as_f32(marker) as i32 {
From some of my testing (which is just having the engine scream when render viewmodel is called), it starts as soon as the demo is loaded. Maybe I miss something during the process but I don't have lots of hope in that getting fixed with just hacks. I can take a look again and give some updates.

2022-12-05 22:08 UTC, khanghugo commented on src/modules/capture/mod.rs
> +            if cls_demos.demoplayback == 1 && frame_count < BXT_CAP_SEEMLESS.as_f32(marker) as i32 {
Also, not only the viewmodel is not rendering but also entities and HUD.

2022-12-05 22:32 UTC, YaLTeR commented on src/modules/capture/mod.rs
> +            if cls_demos.demoplayback == 1 && frame_count < BXT_CAP_SEEMLESS.as_f32(marker) as i32 {
Then it would be nice to find what exactly causes the viewmodel to disappear, if the rendering function is called. Then we can condition on that.

2022-12-08 08:28 UTC, khanghugo commented on src/modules/capture/mod.rs
> +            if cls_demos.demoplayback == 1 && frame_count < BXT_CAP_SEEMLESS.as_f32(marker) as i32 {
It's conditioned but that first frame still won't render any viewmodel. That would be a future fix, totally unrelated fix. But on that, it is possible to skip that frame with the cvar here, which is defaulted to skip it.

2022-12-08 15:59 UTC, khanghugo commented
The only problem with conditioning this variable is it will skipp all the frames if the player carries no weapon. Not perfect unless I find something else.

2023-09-20 03:27 UTC, khanghugo commented
Just re-did this by making it in its own module. Should feel better than before. I recently find myself recording lots of demos and this is indeed very useful to feel less irritating looking at the product(s).

2023-10-23 13:01 UTC, YaLTeR requested changes
> I am also advocating to have this on by default. What do you think?

A bit of a problem with this is that it's natural to try bxt_cap_start in the menu just to test that the recording works--I frequently do this myself.

2023-10-28 06:06 UTC, merged

2023-10-28 06:06 UTC, YaLTeR commented
Thanks

2023-10-31 10:13 UTC, chinese-soup commented
Great addition, thank you, @khanghugo, very cool!